### ISSUE TITLE
Parameterize some settings variables in default_settings.yml

### ISSUE THREAD

**Issue by mnlevy1981** [marbl-ecosys/feisty#39]
The default settings file (`feisty/core/default_settings.yml`) has blocks like

```yaml
food_web:
  # [snip some intervening keys]
  # large demersal
  - predator: Ld
    prey: Mf
    preference: 0.375 #should be A*D = (school_avoid * generalist_reduct)

  - predator: Ld
    prey: Mp
    preference: 0.75 #should be D (generalist_reduct)
```

As the comments indicate, .0375 is really a `generalist_reduct` term times a `school_avoid` term, while the `0.75` is just the `generalist_reduct` term. We'd like to introduce a way to set those two parameters elsewhere in the file, and then have these `food_web.preference` terms change if the user changes the other parameters
